# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest,  r: 'devel' }
          - { os: ubuntu-latest,  r: 'release' }
          - { os: ubuntu-latest,  r: 'oldrel-1' }
          - { os: ubuntu-latest,  r: 'oldrel-2' }
          - { os: ubuntu-latest,  r: 'oldrel-3' }
          - { os: ubuntu-latest,  r: 'oldrel-4' }
          - { os: macOS-latest,   r: 'devel' }
          - { os: macOS-latest,   r: 'release' }
          - { os: windows-latest, r: 'release' }
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (R ${{ matrix.config.r }})
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
          LOGNAME: ${{ env.GITHUB_ACTOR }}
        run: |
          # Hack to get _R_CHECK_THINGS_IN_OTHER_DIRS_ to work
          Sys.setenv("LOGNAME" = Sys.info()[["user"]])
          Sys.getenv("LOGNAME")
          
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "note", check_dir = "check")
        shell: Rscript {0}
